name: cosmostatmap
channels:
  - defaults
dependencies:
  - python=3.7
  - geopandas>=0.6.1
  - jupyter>=1.0.0
  - matplotlib
  - numpy
  - pip>=19.3
  - pip:
    - descartes>=1.1.0
    - geoplot>=0.4.0
    - pyyaml>=5.3.1
