name: CI

on:
  push:
    branches:
     - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.11

      - name: Build conda environment
        shell: bash -l {0}
        run: conda env create -f environment.yml

      - name: Install package
        shell: bash -l {0}
        run: |
          conda activate cosmostatmap
          pip install .

      - name: Build map
        shell: bash -l {0}
        run: |
          conda activate cosmostatmap
          generate_map.py
          mv cosmostat_map.png ./build

      - name: GitHub pages action
        uses: peaceiris/actions-gh-pages@v3.5.9
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
